#define MAGIC_NUMBER 'O'

#define SET_BAUD_RATE _IOWR(MAGIC_NUMBER, 8, int)
#define SET_NO_STOP_BITS _IOWR(MAGIC_NUMBER, 9, int)
#define SET_DIRECTION_WRITE _IOW(MAGIC_NUMBER, 10, int)
#define DEFAULT_DATA _IOW(MAGIC_NUMBER, 11, int)